### ISSUE TITLE
Issues on Wechat

### ISSUE THREAD

**Issue by whatwewant** [whatwewant/play-music#15]
Some Issues on wechat collection

**Comment by whatwewant** [comment]
* Q
  * How to fix page without showing `Powerd by ...` when pull down?
* A
  * Fixed your `body`

```css
body {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
}
```
